---
prometheus_bot_project_url: "https://github.com/Amygos/prometheus_bot"
prometheus_bot_version: "v1"
prometheus_bot_listen_addr: "10.47.107.161:9087"
prometheus_bot_telegram_token: ""
prometheus_bot_template_path: ""
prometheus_bot_time_zone: "Asia/Ho_Chi_minh"

__prometheus_bot_use_template: false
